name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create .env
        run: |
          touch .env
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Copy .env
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: .env
          target: /var/www/trackexpense.app

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /var/www/trackexpense.app
            git pull

            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh

            npm install
            npm run build
            pm2 restart ecosystem.config.js
